# Generated by Django 5.2.1 on 2025-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_manga_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
